export const POSTS_LIST_REQUEST = 'POSTS_LIST_REQUEST';
export const POSTS_LIST_SUCCESS = 'POSTS_LIST_SUCCESS';
export const POSTS_LIST_FAIL = 'POSTS_LIST_FAIL';

export const MAKE_POSTS_REQUEST = 'MAKE_POSTS_REQUEST';
export const MAKE_POSTS_SUCCESS = 'MAKE_POSTS_SUCCESS';
export const MAKE_POSTS_FAIL = 'MAKE_POSTS_FAIL';